### ISSUE TITLE
I can't get it working

### ISSUE THREAD

**Issue by Shnxxx** [OtaK/timertool-rs#2]
I tried installing it and executing different flags but it doesn't show anything. I tried `timerset.exe --install` first then `timerset.exe --values` to check what values can I set but it doesn't show anything. It just creates another process of `timerset.exe`. Also tried `timerset.exe --uninstall` but it created another process of `timerset.exe`. Am I missing something?

![image](https://user-images.githubusercontent.com/48496678/105019941-a4f91380-5a81-11eb-8ddf-77fe9d995965.png)

**Comment by OtaK** [comment]
Sorry for the late answer, I'll publish a new version soon which will be much better.
See #1

**Comment by Shnxxx** [comment]
Thank you for your response! Looking forward to it.

**Comment by OtaK** [comment]
New release is currently building: 
https://github.com/OtaK/timertool-rs/releases/tag/v0.3.0

Cheers!
